version: "1.0"

services:
  app:
    image: node:18.12-alpine
    command: sh -c "npm i && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
